### ISSUE TITLE
Fractional widths don't always work right

### ISSUE THREAD

**Issue by gregturn** [inuitcss/trumps.widths-responsive#3]
I am using desk-1/3 in an app. It seems that in some situations, 33.333333% computes correctly. In other layouts, it happens to result in exceeding the width of the page, and causing an unfortunate wrap. I stripped all the fractional amounts off, (like 33% for 1/3, 16% for 1/6, etc.), and now it all works great. I think that even though it's not perfect, it would be better to be slightly and hence increase the odds that those relatively amounts fit in properly.

**Comment by gregturn** [comment]
As an example, I have the following HTML:

```html
<!DOCTYPE HTML>
<html xmlns:th="http://www.thymeleaf.org">
<head>
    <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'/>
    <title>Drone Aggregator</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, minimum-scale=1.0" />
    <link rel="stylesheet" href="main.css" />
</head>
<body>
    <header class="page wrapper">
        <h1>Drone Aggregator</h1>
    </header>

    <section class="wrapper">

        <ul class="layout">
            <li th:each="guide : ${guides}" class="layout__item lap-and-up-1/2 desk-1/3">
                <div class="media">
                    <img class="media__img" th:src="@{https://drone.io/github.com/spring-guides/__${guide[name]}__/status.png}" />
                    <div class="media__body">
                        <a th:href="@{http://spring.io__${guide[href]}__}" target="_blank">
                            <small th:text="${guide[title]}"></small>
                        </a>
                    </div>
                </div>
            </li>
        </ul>

    </section>

</body>
</html>
```
And the following main.scss:
```css
////////////////////////////////////////////////////////////////////////
// Pre-sets must be done BEFORE a module is imported. Some of these settings are at the top, while others
// are right before the import statement.
////////////////////////////////////////////////////////////////////////

// Spring's palette (found on spring.io)
$spring-green: #6db33f;
$spring-black: #34302d;
$spring-antique-white: #F1F1F1;
$spring-white: #eee;

//$inuit-base-font-size:  12px;
$inuit-base-line-height:  18px;
$inuit-base-background-color: $spring-antique-white;

////////////////////////////////////////////////////////////////////////
// Here are the layers of inuit. Each layer needs to have its order preserved, but modules within the same layer
// can be imported in any order.
////////////////////////////////////////////////////////////////////////

// Settings layer
@import "bower_components/inuit-defaults/settings.defaults";
@import "bower_components/inuit-responsive-settings/settings.responsive";

// Tools layer
@import "bower_components/inuit-functions/tools.functions";
@import "bower_components/inuit-mixins/tools.mixins";
@import "bower_components/inuit-responsive-tools/tools.responsive";

// Generic layer
@import "bower_components/inuit-normalize/generic.normalize";
@import "bower_components/inuit-box-sizing/generic.box-sizing";

@import "bower_components/inuit-page/base.page";

// Objects layer
@import "bower_components/inuit-layout/objects.layout";

$inuit-enable-media--large: true;
$inuit-enable-media--responsive: true;
@import "bower_components/inuit-media/objects.media";

//$inuit-enable-btn--full: true;
$inuit-enable-btn--small: true;
$inuit-btn-background: $spring-green;
$inuit-btn-color: $spring-white;
@import "bower_components/inuit-buttons/objects.buttons";

$inuit-enable-box--tiny: true;
@import "bower_components/inuit-box/objects.box";

// Trumps layer
@import "bower_components/inuit-widths/trumps.widths";
@import "bower_components/inuit-clearfix/trumps.clearfix";
@import "bower_components/inuit-widths-responsive/trumps.widths-responsive";

////////////////////////////////////////////////////////////////////////
// Custom CSS additions and overrides
//
// This isn't to override settings from inuit, but instead, to override or add to CSS generated
// by inuit.
////////////////////////////////////////////////////////////////////////

// Plugin the Ubuntu font
html {
  font-family: 'Ubuntu', sans-serif;
}

// Dress up the top row of a "page"
// Add a small amount of padding at the bottom of a "page"
$inuit-base-spacing-unit--tiny: round($inuit-base-spacing-unit / 8);
.page {
  border-top: $spring-green solid 4px;
  color: $spring-white;
  background-color: $spring-black;
  width: 100%;
  margin-top: 0em;
  padding-bottom: $inuit-base-spacing-unit--tiny;
}

// Wrap a given block with insets so it isn't pushed to the edge of the browser
.wrapper {
  max-width: 1100px;
  margin: 0 auto;
  padding-left: 12px;
  padding-right: 12px;
}

// Fine tune the bar at the top, so it shrinks on portable devices
h1 {
  @include media-query(portable) {
    margin: 0.1em 0;
  }
}

// TODO: Write explanatory comment (can't remember why I made this right now)
.border {
  border: 1px solid;
}

// Extend btn and make it turn into btn--small based on a media query
.btn--responsive {
  @extend %btn;
  @include media-query(portable) {
    padding: $inuit-btn-padding--small - $inuit-btn-border-width  double($inuit-btn-padding--small) - $inuit-btn-border-width; /* [7] */
  }
}
```
